### ISSUE TITLE
Add scrolling active state to table of contents

### ISSUE THREAD

**Issue by bourgeoisrebel** [bourgeoisrebel/everywhere-www#10]
https://www.bram.us/2020/01/10/smooth-scrolling-sticky-scrollspy-navigation/ 

https://css-tricks.com/sticky-table-of-contents-with-scrolling-active-states/ 

Related to #2 which has already configured the 'sticky' position element. 

```javascript
window.addEventListener('DOMContentLoaded', () => {

	const observer = new IntersectionObserver(entries => {
		entries.forEach(entry => {
			const id = entry.target.getAttribute('id');
			if (entry.intersectionRatio > 0) {
				document.querySelector(`nav li a[href="#${id}"]`).parentElement.classList.add('active');
			} else {
				document.querySelector(`nav li a[href="#${id}"]`).parentElement.classList.remove('active');
			}
		});
	});

	// Track all sections that have an `id` applied
	document.querySelectorAll('section[id]').forEach((section) => {
		observer.observe(section);
	});
	
});
```

Add this to css:

```css
.section-nav a {
    transition: all 100ms ease-in-out;
}
```

See if you can figure out [this bit of javascript]( https://ma.ttias.be/adding-a-sticky-table-of-contents-in-hugo-to-posts/#styling-the-table-of-contents) to tidy up the spacing:

```javascript
function clearActiveStatesInTableOfContents() {
    document.querySelectorAll('aside nav li').forEach((section) => {
        section.classList.remove('active');
    });
}
```

**Comment by bourgeoisrebel** [comment]
Have tried examples online but they don't work. Will have to go on backlog.

**Comment by Babaneh1001** [comment]
I tried this on my code and it worked fine, issue is i have a tree like menu list 
1. introduction 
    1.1 lorem ipsum 
    1.2 lorem ipsum
    1.3 lorem ipsum 
        1.3.1 lorem ipsum

and there's a lot of that, the problem is it highlights the whole 1. introduction and the suub menus 
I just want it to highlight them individually when I scroll
